name: Deploy to seller.akevas.com

on:
  push:
    branches:
      - seller

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hostinger
    steps:
      - name: Checkout Code Seller Akevas
        uses:  actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependancies
        run:  pnpm install

      - name: Build App
        run:  pnpm run build

      - name: Add .htaccess to dist/
        run: |
          echo 'Options -Indexes' > ./dist/.htaccess
          echo 'RewriteEngine On' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-d' >> ./dist/.htaccess
          echo 'RewriteRule ^ index.html [QSA,L]' >> ./dist/.htaccess
          
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          switches: -avzr --delete --exclude='api' --exclude='seller' --exclude='delivery'
          path: ./dist/
          remote_path: domains/akevas.com/public_html/seller/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.PORT }}