name: Deploy to Akevas.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hostinger
    steps:
      - name: Checkout Code Akevas
        uses:  actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependancies
        run:  pnpm install

      - name: Build App
        run:  pnpm run build

      - name: Add .htaccess to dist/
        run: |
          echo 'Options -Indexes' > ./dist/.htaccess
          echo 'RewriteEngine On' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-d' >> ./dist/.htaccess
          echo 'RewriteRule ^ index.html [QSA,L]' >> ./dist/.htaccess
          
      - name: Deploy via SSH (Rsync)
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: domains/akevas.com/public_html/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.PORT }}
