name: Deploy to Akevas.com

on:
  push:
    branches:
      - seller

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hostinger
    steps:
      - name: Checkout Code Akevas
        uses:  actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependancies
        run:  pnpm install

      - name: Build App
        run:  pnpm run build

      - name: Copy .htaccess to dist/
        run: cp .htaccess ./dist/.htaccess
          
      - name: Deploy via SSH (Rsync)
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude='api' --exclude='seller' --exclude='delivery'
          path: ./dist/
          remote_path: domains/akevas.com/public_html/seller/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.PORT }}